# Generated by Django 5.2.7 on 2025-10-25 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('sport', models.CharField(choices=[('gym', 'Gym & Fitness'), ('football', 'Football'), ('futsal', 'Futsal'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('swimming', 'Swimming'), ('yoga', 'Yoga'), ('martial_arts', 'Martial Arts'), ('golf', 'Golf'), ('volleyball', 'Volleyball'), ('running', 'Running'), ('other', 'Other')], default='other', max_length=20)),
                ('hourly_fee', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
