# Generated by Django 5.2.7 on 2025-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coach_id_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
