# Generated by Django 5.2.7 on 2025-10-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_commentvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
