# Generated by Django 5.2.7 on 2025-10-25 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tipeTournaments', models.CharField(choices=[('gym', 'Gym & Fitness'), ('football', 'Football'), ('futsal', 'Futsal'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('swimming', 'Swimming'), ('yoga', 'Yoga'), ('martial_arts', 'Martial Arts'), ('golf', 'Golf'), ('volleyball', 'Volleyball'), ('running', 'Running'), ('other', 'Other')], max_length=50)),
                ('namaTournaments', models.CharField(max_length=100)),
                ('tanggalTournaments', models.DateField()),
                ('lokasiTournaments', models.CharField(max_length=200)),
                ('deskripsiTournaments', models.TextField()),
                ('posterTournaments', models.URLField()),
                ('flagTournaments', models.BooleanField(default=True)),
                ('idTournaments', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pembuatTournaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coach')),
                ('pesertaTournaments', models.ManyToManyField(blank=True, to='users.member')),
            ],
        ),
    ]
