# Generated by Django 4.2.25 on 2025-10-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tipeTournaments',
            field=models.CharField(choices=[('gym', 'Gym & Fitness'), ('football', 'Football'), ('futsal', 'Futsal'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('swimming', 'Swimming'), ('yoga', 'Yoga'), ('martial_arts', 'Martial Arts'), ('golf', 'Golf'), ('volleyball', 'Volleyball'), ('running', 'Running'), ('other', 'Other')], max_length=50),
        ),
    ]
