# Generated by Django 5.2.7 on 2025-10-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='slug',
        ),
    ]
