# Generated by Django 5.2.7 on 2025-10-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
