# Generated by Django 5.2.7 on 2025-10-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_message_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
