# Generated by Django 5.2.7 on 2025-10-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('users', '0003_coach_description_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='coach',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='users.coach'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='users.member'),
        ),
    ]
