# Generated by Django 5.2.7 on 2025-10-23 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-start_time', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='coach',
            field=models.ManyToManyField(blank=True, to='users.coach'),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='member',
            field=models.ManyToManyField(blank=True, to='users.member'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='coach_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sport_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
    ]
