<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-25 16:17
=======
# Generated by Django 5.2.7 on 2025-10-25 16:33
>>>>>>> tournament-modul-salman

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='users.coach')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to='users.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('coach', 'reviewer'), name='unique_reviewer_coach_once')],
            },
        ),
    ]
